# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: read

on:
  pull_request:

env:
  GO_VERSION: "1.24.4"

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "go.sum"
      - name: Run Download
        run: go mod download
      - name: Run vet
        run: CGO_ENABLED=0 go vet ./...
      - name: Run staticheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -checks=all ./...
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -show verbose ./...

  tidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "go.sum"
      - name: Run tidy
        run: go mod tidy --diff

  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [oldstable, stable]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -race ./...

  spelling:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spell check repo
        uses: crate-ci/typos@v1
